name: build-release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  release_policy:
    runs-on: ubuntu-latest
    name: build
    steps:
    
    - uses: actions/checkout@v2

    - name: Build Policy 
      id: aserto-build
      uses: aserto-dev/aserto-build-action@v2
      with:
        source_path: src
        target_path: build
        target_file: bundle.tar.gz
        revision: "$GITHUB_SHA"
        verbose: true

    - name: Release Policy
      id: release
      uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "build/bundle.tar.gz"
        tags: true
        draft: false
        verbose: true

    - name: Push Policy 
      id: aserto-push
      uses: aserto-dev/aserto-push-action@v2
      with:
        bundle: build/bundle.tar.gz
        release_id: ${{ steps.release.outputs.release_id }}
        policy_registry: https://bundler.eng.aserto.com/v1
        policy_id: ${{ secrets.PI }}
        tenant_id: ${{ secrets.TI }}
        policy_registry_key: ${{ secrets.PUK }}
        verbose: true
